# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "b1FzwMcoMuHBdn9y9u/5UxBl/cTWiMj8rQww8B5brSQjLR16d1uRQBOlDKwYHMnv8sFOgl6D3vvsYICFm6eVnXd9mKYGcPqD2k+YoVAQCzQelrGz9ra2ddqNVgoIbiIcAzlHETiu76b6+8svU+9kZ3npEUFCkU9rbzYod3M5s/hcC5bCrS4qamN2G/wYqot2cATBgHvuoDDc8secEb5xdT3i4JXgisvr0N9M6ObaVwFQsA9zD2aCwljjN7WWGdzY4F06koqPVF1pcAE+koeHmVvP2fEouCyiwZ4eJIK/gfmAwNpdb8GOtRv6yed4WjYL+mJ1e6KHeH97biXZsdqUynXwS3fcUVQPd46ldiFjJJLQIDKSwoGBPZhRgKvf8Mh1Z67Z+7YCUzjUE9J5VTwtrmcUtVPyYxjtB0zjInXK73QQ+xv8phQzE3tPFZA6kq38PTrp+jv6+toiTFslk96zwMM4qF2LhCoid+gmEARbUVRRIrsXHlTAT1lYswAclRrmCVlY7AdKe0WNPzzGM9/n6m3teGVHaX4k0T/oqYtgAfWEoNzhfnSIjtcWoPqi1kl64v4Gy8ch8dCwZKwcbbwOjA9Ard6xtdcToPgC6WPLX5lPNr0jBCVOSvKwbiE0U43HaMb0yvcdGa9umRbYTNsvBBG1/4U58z/zmOlXAGpTApU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
