travis:
  secure:
    BINSTAR_TOKEN: MmLSH3hgvhh3YIspovuMflUP4AG+TCOQK6KP2FZaktLJq6qfBF5+EDcY02jtv4Hg7CINd0SwgVL+DLwe/L/DwFCU5d3VeJcxipW1KwHgoiCltzR85hP2bhOjvI2kPsmXxhCQwx7UgUGmxG63dW+wCKHRKWY1fjIktA97zHtJA/MbAZwx5e0LJh1ZZ1wKcRqds7vcedJQ8VG6g/gl/XsL9pxCy/asmU4x7TgsldK48DELMMZiJm80mfE+g/LZlSnNd6NARixNAMl/a1s+bN2pu1XTljHvuadzgieVJt7mYjGqQMsPYKt4bzkkpzKs+lG01vL2e5HD7+/2Y2zNmVoqQSQVkYxIwKJLrYenYsCxmiGb7YsecAq1vITCN7qwN1HtsCo3WmdukfVtTyxS9pmbRQ5n6Dg1QwQNbBKqjtPZCQy6OuEiqnfreQ1lHEc9qYSpG8tUGmoRPulm45jPK+txqDVLpm8t83OndTw0lPy+eGz0wsgot7ERmsHHUvqY/V3Eh4CK/ScR5bAMaxtaj46r6adZTVV803UFbzw7vGsqXBgbDH10R78hqqHK3tvMT9al3uB7kSwaU/c9fyz6+y127zNEdBst2vnUeXwz1+oZGzg7qok9S3May63DMNxqGNiFMK5Jj5wfFVguyhsOUMP6nE0Le89VjFQtYiDJq2HioAI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
