travis:
  secure:
    BINSTAR_TOKEN: a/HYF30hfX4b3bqp6oGwzI4ANUaUTFINWZotL+W4Jph1+fCp7IbxQEnsSc3JOnLWJH9Pg5Y2iy+8MJq2dQiwwtiKFM5nT5g/5qwboPU1p10W18WgmRY0bU+cMzEZuV3OQHqo4rJxWSf8PwKfz/LjzEATme34LmNMVeT7nsfNTRCI+a26yDjaNfkuehKrviKoQOqmSWNmlXlW9VFSSL00pl6xHwe45Oyr5RDhKbcvWA22LKebLg+YA8+QzR8LjqLKidy78oql7nfPlr6hWEgn22EATGK1jsrChfnYJyrkcgFUvIcLlXdeagt2PHq4pqQDUrpqHnnZyiNr0cp3EWzo72EGt1zqkSmpzfpjQ3nJ9BnOQw3BScn1h1L77vlbk9udiJXTBlYs/h9xV6R4ak05ZZkcjqVfe0bl3a4mm+RcNN5SrhBhrl70X3JhPDvge/6UkBF3vcQAAfz2oHis7t0nevXKNXYw2vSMSegYB/ltalvjQqVa8wVKAgvTkBhUCwu0u+rrIypnbfTvXA26rgxciOaUWJhmJwM/SrLfOfQ7hcfia7jb4TMydBSZOLVtiQ1Zr7UO8AguNyZHowt7k8UrF5oGTYizlWJt8nWNlE9El80WyrzHzbDwbRpiR6xHIeAmNVaJU9KwPmbpcK3Vwlcesi8EeQn1YsgTL/JkAQgrc+8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
