travis:
  secure:
    BINSTAR_TOKEN: gyfel0FXWk9PdxArvkFpZV+qQMpsqZudaL+/eR2JJF2CU7nB0EiEAo/Y+4g/AoTzjDMgNIGpHwsssEU/xzlBn+jFm+2PYlGCxHeafTXLCtRba0VMWieW4/96QEdc6BmmUzkVFcYoQTAl+cYo0t7/TZhkbe0l/MCGKSeEeFDGkFhMyJSL7PPCM3SwVxDjzAVvvHh/F9THGeWXA4HmEf8iWsTHD/UfMxqJDuMkPknukOjQAFCtQQuI6k5BS3Pj0d+hMytMaYmAFTF86ioRqwN70Gu4azrvnJimZ7tLhYmCCUUViUezGr2Zgu3VMa3ux6UN83ilqfWsV8t0E7xUdjLK76GCRsT8J62H0G9CNz3QD5DthcXnVLSl06FYfm6Ogwm9fa77h3tAdUkjSG8mnTYiv8d5eodGV9x7dCKxyhdY6eVUQH/4MkXcu7YdDw9yAKCBG2V9zL/oB0sFy7mOasQB/Rb/kXD/K5EvS2Lq1qrMUO/6Hcz/WVy2LAaYvQzWG071uBdSw9WF6YnLXh5iIO/FgxMmWxBz48D+prsGGctkkcxO6HM2YwELrQWoU8FuWjoYo3UcTqMLN47Crz3eUc+OJhS5zuEQjNkUQUOXexrpeinloGpqOaB/nkT+YRNhY+AHyYmIBu0OGQCkzsrYWR8bloMLH6j0plzT0XoWCgDVmds=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
