travis:
  secure:
    BINSTAR_TOKEN: b1FzwMcoMuHBdn9y9u/5UxBl/cTWiMj8rQww8B5brSQjLR16d1uRQBOlDKwYHMnv8sFOgl6D3vvsYICFm6eVnXd9mKYGcPqD2k+YoVAQCzQelrGz9ra2ddqNVgoIbiIcAzlHETiu76b6+8svU+9kZ3npEUFCkU9rbzYod3M5s/hcC5bCrS4qamN2G/wYqot2cATBgHvuoDDc8secEb5xdT3i4JXgisvr0N9M6ObaVwFQsA9zD2aCwljjN7WWGdzY4F06koqPVF1pcAE+koeHmVvP2fEouCyiwZ4eJIK/gfmAwNpdb8GOtRv6yed4WjYL+mJ1e6KHeH97biXZsdqUynXwS3fcUVQPd46ldiFjJJLQIDKSwoGBPZhRgKvf8Mh1Z67Z+7YCUzjUE9J5VTwtrmcUtVPyYxjtB0zjInXK73QQ+xv8phQzE3tPFZA6kq38PTrp+jv6+toiTFslk96zwMM4qF2LhCoid+gmEARbUVRRIrsXHlTAT1lYswAclRrmCVlY7AdKe0WNPzzGM9/n6m3teGVHaX4k0T/oqYtgAfWEoNzhfnSIjtcWoPqi1kl64v4Gy8ch8dCwZKwcbbwOjA9Ard6xtdcToPgC6WPLX5lPNr0jBCVOSvKwbiE0U43HaMb0yvcdGa9umRbYTNsvBBG1/4U58z/zmOlXAGpTApU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
